### ISSUE TITLE
Latest additons

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#10]
Display a short (5-10) list of latest edits and additions
(ie new project added, new source added)

**Comment by byndcivilization** [comment]
Do we want modules for each entity type? if so which entities? if not, do we just want something like entity - type with a hyperlink? Do we want a list of recent sources?  We can use the [entity]_established filed on the entities to get this i think.

**Comment by davidmihalyi** [comment]
No need for it to be on each entity type.
I think having something on latest new projects or country or source might be useful, but let`s keep it simple.

**Comment by byndcivilization** [comment]
moved to #114
