### ISSUE TITLE
Field for assigning company share of a project

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourceprojects.org#10]
For projects in oil and gas multiple companies will often share ownership of a given project. Each will have an assigned share.

Example from EITI 2011 report for Jubilee field Ghana: 

Ghana	Oil	Oil		Jubilee Field			Tullow Ghana Limited (Operator and holder of 34.7% interest)	
Ghana	Oil	Oil		Jubilee Field			Kosmos Energy (23.5%)	
Ghana	Oil	Oil		Jubilee Field			Anadarko Petroleum (23.5%)	
Ghana	Oil	Oil		Jubilee Field			Ghana National Petroleum Company (13.8%)	
Ghana	Oil	Oil		Jubilee Field			Sabre Oil & Gas (2.8%)	
Ghana	Oil	Oil		Jubilee Field			E.O. Group (1.7%)

**Comment by timgdavies** [comment]
The model includes the notion of a ```Stake``` entity between companies and projects, and the Stake has a ```share``` property, as well as ```startDate``` and ```endDate``` so we can capture the temporal change in ownership.
