### ISSUE TITLE
Custom landing pages for special sources

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/ResourceProjects.org#11]
We need special landing pages that display things like payment data aggregated by company etc for soruces like UK disclousres, norwegian disclosures, eiti project level payments, voluntary sources. Some of these are comming from multiple source entities. This means we may need to institute some sort of source manual clustering.

**Comment by davidmihalyi** [comment]
It may come from different imported tables, but our current template has cells on original source for each payment record. The source has a name, a type (mandatory payment disclosure, EITI, etc.), format (PDF, doc, API) and  year. This should allow to sort and cluster the information needed.

**Comment by byndcivilization** [comment]
Need to introduce bulk download feature.
Includes: Download all UK payment disclosures from CH . (this is two tables: one by payment type, one py payment to what entity)
Download all payment data

**Comment by davidmihalyi** [comment]
See source codelist:
https://docs.google.com/spreadsheets/d/16vuQCT92gYsMGGNGgX-j12-giCmO3SrUak6cG8oulMM/edit#gid=145722551 

These are the ones that need to be diplayed on payment information.
Source Authority	Source Type	Identifier	Examples
Authoritative source	- Voluntary payment disclosure	vpd	Voluntary company disclosure - (eg. http://www.kosmosenergy.com/responsibility/transparency.php)
Authoritative source	- Mandatory payment disclosure	mpd	Mandatory company disclosure (eg. http://www.detnor.no/wp-content/uploads/2015/03/DETNOR-Annual-Report-2014.pdf?d5b1f2 )
Authoritative source - 	EITI report	eiti	EITI report (eg. https://eiti.org/files/EITI-2010-2011-oil-final.pdf)

**Comment by byndcivilization** [comment]
those dont really help. We need to bundle certain sources together (UK disclosure years for instance). Mandatory disclosure type will just get you all the mandatory disclosures.

**Comment by davidmihalyi** [comment]
we could add a subcategory within source type for a further layer of breakdown where useful (UK vs Norway etc)

**Comment by byndcivilization** [comment]
When we display these what do we call them? Disclousures? Payment clusters? Source clusters?

**Comment by davidmihalyi** [comment]
These are all project level payment data. It`s source can be 
UK mandatory payment disclosure
Norwegian mandatory payment disclosure
... (more to be added such as France, Canada, .. but that is it for now until launch)
voluntary payment disclosures
EITI report with project level payment data

**Comment by davidmihalyi** [comment]
we could add an "other" field, as we may want to display information that is neither.

**Comment by byndcivilization** [comment]
right now we are storing a source type collection:
```{
    source_type_name: String,
    source_type_id: String, // loaded, edit. api
    source_type_authority: String,
    source_type_examples: String,
    source_type_url_type: String,
    source_type_notes: String
}```

**Comment by byndcivilization** [comment]
We can use these source types as the collection point for sources -> transfers (payments) and production records. It also gives us the option of storing source type metadata if we need a little additional bundled info. right now we are adhering to the code list in the google sheet. Id like to lay out proposed changes here for clarity:

- Voluntary payment disclosure (generic) --- vpd
- Mandatory payment disclosure --- mpd
- EITI report --- eiti
- Government report --- govreport
- Government database --- govdb
- Other authoritative source --- otherauth
- Extractive company report --- companyreport
- International organization report --- ioreport
- Company database --- companydb
- Wikipedia --- wikipedia
- Google maps --- googlemaps
- Press article --- press
- Other non-authoritative source --- ???

proposed additions:
- UK mandatory payment disclosure --- ukdis
- Norwegian mandatory payment disclosure --- nodis
- additionals = iso2+dis
- Other --- other

@davidmihalyi are you asking for separate voluntary payment disclosure types and a type EITI report with project level payment data above basic eiti report?

**Comment by davidmihalyi** [comment]
no further breakdown of voluntary payment disclosures I can think of is needed.
Good idea to breakdown EITI reports into:
EITI report
EITI report with project level payment data.

**Comment by byndcivilization** [comment]
Can we move this to hard launch since we dont really have any of these we want to diplay yet?

**Comment by byndcivilization** [comment]
@davidmihalyi

**Comment by davidmihalyi** [comment]
We can get away by saying what we will see for some features.

But I think the payment list page should at least allow to browse across vpd and nodis sourced (payment) projects.

**Comment by byndcivilization** [comment]
I can tell you now it's not likely to happen by soft launch.

**Comment by byndcivilization** [comment]
Something has to give as soft launch becomes hard launch.

**Comment by davidmihalyi** [comment]
Gotcha! I will work on some text to display on the page, if that can go there.

Sent from mobile;  pls excuse brevity and typos.

On 24 Mar 2016, at 10:57, Chris Perry <notifications@github.com<mailto:notifications@github.com>> wrote:


Something has to give as soft launch becomes hard launch.

-

**Comment by byndcivilization** [comment]
this will be bumped to hard launch if time doesnt allow

**Comment by byndcivilization** [comment]
moved to #116
