### ISSUE TITLE
Core ISO codes

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourceprojects.org#11]
Confirm the core classifications: 

- Country: ISO 3166-1 alpha-2?, http://www.iso.org/iso/home/standards/country_codes.htm
- Currency: ISO 4217, http://www.iso.org/iso/home/standards/currency_codes.htm

**Comment by timgdavies** [comment]
I think we should be able to confirm this pretty easily.

**Comment by timgdavies** [comment]
I can confirm we are using ISO 3166 alpha-2 for countries, and ISO 4217 for currency.
