### ISSUE TITLE
Source type page description is misleading

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#110]
This may be my fault, but current description/example here is misleading for UK disclosures:

"Examples:	Mandatory company disclosure (eg. http://www.detnor.no/wp-content/uploads/2015/03/DETNOR-Annual-Report-2014.pdf?d5b1f2 )"

http://resourceprojects.org/source_type/56e8736944442a3824141429

The example is from Norway.
Maybe drop or hide for now?

**Comment by byndcivilization** [comment]
@davidmihalyi can we get a correct link?

**Comment by davidmihalyi** [comment]
Examples:

UKDIS: Shell 2015 mandatory disclosure: http://www.shell.com/sustainability/transparency/revenues-for-governments/_jcr_content/par/textimage.file/1460962925009/e06222a6095a4986d6d0802c8de9a699/shell-report-payments-to-governments-2015-18042016.pdf

FRDIS: Total 2015 mandatory disclosure:  
http://www.total.com/sites/default/files/atoms/files/form_20-f_2015_web_version.pdf

NODIS: Statoil 2015 mandatory disclosure:  http://www.statoil.com/no/InvestorCentre/AnnualReport/AnnualReport2015/Documents/DownloadCentreFiles/01_KeyDownloads/2015%20Payments%20to%20governments.pdf

**Comment by byndcivilization** [comment]
You can edit these in the administration drop down.

**Comment by davidmihalyi** [comment]
Awesome!

**Comment by davidmihalyi** [comment]
this is not live yet, right?

**Comment by davidmihalyi** [comment]
but the admin function is there on staging site...
would change on staging stite also change the main site?
I don`t understand clearly how this works...

**Comment by davidmihalyi** [comment]
sorted!
