### ISSUE TITLE
Source bundle page

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#111]
If we have a customized source type bundle page, with 
UKDIS
NODIS
EITI at forefront,
then useful to also put 
Voluntary disclsorue at forefront.(vpd)
(and any subsequent disclosures, like french)
See also issue #11

**Comment by davidmihalyi** [comment]
Note, that Total was mis-classified by me, it now still appears as UKDIS, but will disapear from there after reload (it is FRDIS).

UKDIS should include Shell (via API), but it does not show. 
Maybe waiting for a push of Smarlane updates?

NODIS is not loading, maybe too many data.

**Comment by byndcivilization** [comment]
moved to #127
