### ISSUE TITLE
source links break due to http:// repetition

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#112]
Source data is stored messily, hence it does not always show right URL
http://resourceprojects.org/source/574f10d681e91c32004e793d

this was solved for OC corporate link and company website, so might just need to apply same code.

**Comment by byndcivilization** [comment]
@davidmihalyi Is this still an issue?

**Comment by davidmihalyi** [comment]
yes, sitll an issue. 
It seems to add http:// even when already there.

**Comment by mattfullerton** [comment]
I've added a simple http:// appender for source url, source archive url, company website and company group website. I've removed http appendage in the template for source url and source archive url. CH has full control of the link as the source is CH and was already using https.
