### ISSUE TITLE
Template Improvements

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/ResourceProjects.org#124]
- Use named columns internally instead of column numbers
- Use new information from 0.6 correctly, removing assumptions/workarounds as appropriate
- Convert all spreadsheets to 0.6 format

Task breakdown:
- Named columns - 1 day (includes checking that existing import still references data correctly and works properly)
- 0.6 Import - 1.5 days (this includes an inevitable amount of communication overhead to make sure we match spreadsheet and model)

**Comment by mattfullerton** [comment]
Done
