### ISSUE TITLE
Reconciliation interface

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/ResourceProjects.org#126]
- Change use of Aliases to embedded documents instead of references
- Create dummy duplicates based on CH dummy import
- List duplicates with some details in the reconciliation interface (including Angular controller, etc.)
 -Provide following functions for each duplicate (where the word “parent” is a shorthand for the XY property above):
- Use the parent entity instead: the new information is a pure duplicate. The name is added to that parent entity as an Alias and the Duplicate is marked as isDuplicate: true. All references to the entity (Links, Facts?, ImportSources) should be changed.
- “Merge” - (N.B. - this may need some further discussion, not included in the time estimate: what is the workflow for updating entites with newly discovered info?)
- “Not a duplicate” - mark the duplicate as resolved optionally with some notes. The duplicate entity remains so that future imports do not require new admin action.
- Update GS and CH imports for duplicates model (GS: Remove duplicate creation, CH: mainly adding search for existing duplicates)
- Test entire workflow especially usage of Aliases

Task breakdown:
- Change use of Aliases to embedded documents instead of references - 0.5 days
- Create dummy duplicates based on CH dummy import combined with one GS import - 0.5 days
- Interface functions (api functionality) - 1.5 days
- Update GS and CH imports for duplicates model (GS: Remove duplicate creation, CH: mainly adding search for existing duplicates) - 1 day
- Test entire workflow especially usage of Aliases - 1 day
- “Mark cleaned” function for pipeline work above, including consideration of duplicates removal - 1.5 days

To be performed by Frontend developer:
- List duplicates with some details in the reconciliation interface (including Angular controller, etc.)
Interface functions (UI)

**Comment by mattfullerton** [comment]
More precise explanation of frontend task:

- A reconciliation interface (prototype is here: /public/app/admin/etl/reconcile.jade)
- This should use this endpoint to get (/api/duplicates GET) the current duplicates. They are structured according to the server/models/Duplicates.js
- Actions that can be taken are "resolve" (-> not a duplicate), setasalias (set the duplicate's name as an alias of the parent but don't do anything with the data), update (move the info from the duplicate into the "parent"). I think for now just offer resolve and update (i.e. not a duplicate or is a duplicate), I think we will end up combining setasalias with update.

To generate some duplicates: just run an import (e.g. one of the google sheets) and then call the endpoint /api/identifyduplicates - it will find some things.
