### ISSUE TITLE
UK CH data country reconciliation

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#133]
What method did you use for country name reconciliation?
Shell has some 3 digit country ID, but in many country cases (ie Nigeria) the country data does not show in the ETLd Shell data.           http://staging.resourceprojects.org/admin/etl/datasets/56737e170e8cc07115211ee4/actions/5755f424a6cac30e0083e002/report
                                vs            
https://extractives.companieshouse.gov.uk/api/company/04366849/year/2015/xml

**Comment by mattfullerton** [comment]
We think this is fixed. Waiting for production test before closing.

**Comment by davidmihalyi** [comment]
This works!
