### ISSUE TITLE
ETL: Make all company names proper case? OR enforce case insensitive company name checking for GS import (done for CH)

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/ResourceProjects.org#135]
CH API has things capitalized, suggestion would be to transform to proper case and/or use case insensitive checks everywhere (this would not produce duplicates but rather assume a perfect match).

**Comment by davidmihalyi** [comment]
This would be great to do!

**Comment by mattfullerton** [comment]
Done in GS. Closing.
