### ISSUE TITLE
Two reports merged somehow from CH API 

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#139]
Bisichi is mixing into data on Fresnillo under payments. Unclear why, Bisichi is standalone company with single south african mine and zero payment.

Fresnillio:
http://resourceprojects.org/company/576843c7be87580e00048237

Bisichi:
http://resourceprojects.org/company/576843cbbe87580e0004828e

**Comment by mathiascbaur** [comment]
There were really some information mixing while processing reports asynchroneusly. Now everything should be seperated cleanly.
Should be tested after deployment before closing.

**Comment by davidmihalyi** [comment]
Thanks Mathias!
Anything that needs to be done when new reports come in?

**Comment by mattfullerton** [comment]
Closing
