### ISSUE TITLE
CH Import: set project country and rely on project name/alias AND country for matching

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#146]
It seems like projects with same name, but in different countries are merging at least with data from UK CH providing strange results.

We have growing number of projects that are just called `Block X` in each country.

For example:
http://resourceprojects.org/project/uy-bl6-2qnu8h
The unique project ID (based on Uruguay) picked up data on both in Uruguay and Oman and has merged it.

Can you check whether this ETL problem or happens later in the chain?

Also important insight for deduplification process.

**Comment by davidmihalyi** [comment]
similar problem arised with two datasets where neither were UK CH, both were ETL via spreadsheet.

Seems like project is both in Azerbaijan and Angola:

**Comment by davidmihalyi** [comment]
http://resourceprojects.org/project/az-bloc-djn2u9

**Comment by davidmihalyi** [comment]
Weird thing is that Statoil does not have a project called block 40

**Comment by mattfullerton** [comment]
In any case my suggestion is to always flag a duplicate if a project has the same name and not to attempt to reuse. Doing unique names per country is difficult as a project location has been removed and theoretically a project could extend over multiple countries. Project+Source doesn't really work as theoretically one source could describe two same-named projects in two different countries.

In the CH import we avoid ever reimporting the same "report" so reloads should not cause the projects to get recreated. A small problem is new versions of the same report. These count as new sources but are likely to contain almost the same information. Here I would suggest we do an unload of anything connected with the prior source automatically. On the other hand if the interface is slick enough quickly checking that the "new" projects are all the same as the old ones would not take much time.

**Comment by mattfullerton** [comment]
The main problem here was assuming project names are unique. In GS import I now only assume they are unique per country. @mathiascbaur Is it possible for you to do the same; can we successfully guess in which country a project takes place? If not we will have to not reuse projects in CH import and rely on duplicate detection afterwards. @fschimandl It is important that duplicate detection uses country info: if its there and different between projects it can't be a duplicate; if it is not there then there can be a free match on projects with similar name from any country.

**Comment by mattfullerton** [comment]
Ha! Sometimes the 2 letter country code is in the project code in the API. Sometimes its the 3 letter code. And sometimes, it just isn't there at all!

Anyway, using it where I can.

**Comment by mattfullerton** [comment]
While I was at it I stopped using the transfer countries as information about project location. Good/bad?

**Comment by mattfullerton** [comment]
In general my advice is to perform Google Sheets imports first where we have better chances of having project country.
