### ISSUE TITLE
ETL: Productions not getting linked to companies

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/ResourceProjects.org#150]
This was being done as production.company, but the DB and controller require a link instead.

**Comment by mattfullerton** [comment]
@byndcivilization maybe you can comment here on which things should be linked and which fields (if any) in the DB are deprecated. Right now I create no links for productions.

**Comment by byndcivilization** [comment]
@dmihalyi I remember there being a decision not to link production values to companies. Can easily add it in if that has changed.

**Comment by mattfullerton** [comment]
Now that I've redone the production and transfers (payments) imports, it seems fairly clear to me that the "links" are all being done using fields in the model and not using links. Companies are  attached in this way to productions and transfers. If this continues to be a problem after we see the new staging version please reopen and rename, as it is probably then down to confusion in the controller(s).
