### ISSUE TITLE
populate source type list page with unique project counts and unique country coverage

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/ResourceProjects.org#153]
Projects are a must, countrys need to be done if possible. The current issue is that we need to get the list of associated project ides from a couple of place and its requiring mongoose to go to far down the nesting hierarchy to be able to iterate through normally. we find associated countries through associated projects. we find associated projects through both 'links' and through the 'proj_established' variable. I feel like there is some sort of obvious asynch solution im missing here but cant quite wrap my head around it.

**Comment by byndcivilization** [comment]
please see the feature-add-payment-page branch for latest code on this

**Comment by davidmihalyi** [comment]
@KseniyaKuprina  is this page already pushed to staging site?
