### ISSUE TITLE
Review concessions API from Open Oil

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourceprojects.org#16]
Open Oil has launched an API with concession layer data. The API should contain the following fields: 

ConcessionName [string]	
ConcessionContractor [string]	
ConcessionDescription [string]
ConcessionSource [url]	
ConcessionSourceDate	[date]
Retrieved at [date]

More on the methodology here: http://repository.openoil.net/wiki/Concession_Layer_Methodology

Description here: https://openoil.net/2015/05/22/come-and-get-it-openoil-publishes-first-open-api-for-oil-rights/

**Comment by timgdavies** [comment]
Reviewed and referenced in addressing #13

**Comment by anderspeders** [comment]
Great, I wonder if that means - will we be importing the data from the concession API inclduing the sourcing?

**Comment by timgdavies** [comment]
Happy to have a look at importing this data - but will need to confirm the level of priority to give this for the end of the current sprints...

**Comment by anderspeders** [comment]
New idea for method for adding data from Open Oil concession API: 
If there is a hit on a project or company the concession name and metadata can be imported.

**Comment by timgdavies** [comment]
I have a script set-up that can convert Open Oil data into our data model at https://github.com/NRGI/resource-projects-etl/tree/master/process/openoil-api

Whether or not we want to import the full OpenOil concessions data is something to think about.
