### ISSUE TITLE
Should unload be possible AFTER reconciliation? Should unload be possible at all???

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/ResourceProjects.org#161]
A slight concern. At various points we search for existing entities and either:
- Update
- Create a new one which will be flagged as a duplicate

I think it makes sense to only allow unloading in the "unclean" state, before duplicates have been dealt with/merged. Otherwise the data in entities supplied by multiple imports is linked to multiple imports; these entities will not be removed when removing the data of one import but the data within them is "contaminated" by the 2nd import. One option would be a kind of cascade that warns that the data of other imports also has to be removed.

In the update case we have the problem straight away before and after cleaning.

The more I think about the more I think the cascade option is the better one. The data model remains the same but the action when unloading is different/more drastic.

**Comment by davidmihalyi** [comment]
I need to discuss to get more clarity.

**Comment by mattfullerton** [comment]
This has been resolved. "Contaminated" entries can only come from loading a new dataset where merging takes place for those entities. Unloading does not undo the contamination, but reloading (which we assume someone will feel compelled to do) with corrected data will fix.

I would be tempted to disallow unloading after cleaning is finished until we see whether we really need such a facility (the functionality would be more or less there but out of bounds).
