### ISSUE TITLE
UI: Tether version conflict

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/ResourceProjects.org#162]
On a fresh `bower install` I'm getting this message:
Please note that,
    angular-mocks#1.3.2 depends on angular#1.3.2 which resolved to angular#1.3.2
    angular-animate#1.3.20, angular-resource#1.3.20, angular-route#1.3.20 depends on angular#1.3.20 which resolved to angular#1.3.20
    angular-tether#0.2.3 depends on angular#~1.3.8 which resolved to angular#1.3.20
    resource-projects-frontend depends on angular#~1.3.2 which resolved to angular#1.3.20
    angular-sanitize#1.4.10 depends on angular#1.4.10 which resolved to angular#1.4.10
    angular-nvd3#1.0.8, angular-plotly#0.1.2 depends on angular#^1.x which resolved to angular#1.5.8
    ng-csv#0.3.6, ngDialog#0.3.12 depends on angular#~1 which resolved to angular#1.5.8
    angular-spinner#0.8.1, restangular#1.5.2 depends on angular#~1.x which resolved to angular#1.5.8
    angular-filter#0.5.9, angular-tablesort#1.1.2 depends on angular#* which resolved to angular#1.5.8
    angular-leaflet-directive#0.10.0 depends on angular#1.x which resolved to angular#1.5.8
    ngInfiniteScroll#1.2.2 depends on angular#>=1.2.0 which resolved to angular#1.5.8
    angular-google-analytics#1.1.7 depends on angular#>=1 which resolved to angular#1.5.8
    textAngular#1.5.3 depends on angular#>=1.3.x which resolved to angular#1.5.8
Resort to using angular#~1.3.2 which resolved to angular#1.3.2
Code incompatibilities may occur.

Please note that,
    angular-tether#0.2.3 depends on tether#~0.6.5 which resolved to tether#0.6.5
    bootstrap#4.0.0-alpha.3 depends on tether#^1.1.1 which resolved to tether#1.3.3
Resort to using tether#^1.1.1 which resolved to tether#1.3.3

Unfortunately this means that the tether files are under a "dist" foldern and can't be found leading to a series of web console errors. Finding some compatible arrangement of angular-tether and bootstrap might fix this (bootstrap 3???)

**Comment by KseniyaKuprina** [comment]
Matt, are you sure about Bootstrap3? Because, before Bootstrap4 was there?

**Comment by mattfullerton** [comment]
I only meant that it is Bootstrap 4 that is causing the problem... and/or
angular-tether, but I imagine changing angular things is more difficult.

**Comment by mattfullerton** [comment]
@KseniyaKuprina Is this really fixed? I've seen no changes in bower.json and I'm still getting the error. Delete public/vendor and fresh bower install to generate the error.
