### ISSUE TITLE
ETL: persist project IDs

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/ResourceProjects.org#164]
Idea: write them into the google sheet and if they are there use them and don't autogenerate. If they exist and are not in the sheet (i.e. same project in two sheets), put them there too to prevent conflicts.

**Comment by mattfullerton** [comment]
@davidmihalyi Related question: should the project codes supplied in the extractives API be used here? Currently they are adopted as project ID.

**Comment by davidmihalyi** [comment]
I am actually surprised that UK API generated projects don`t get a project ID according to our convention. Is this because of the lack of country codes in some places?

**Comment by mattfullerton** [comment]
I meant to edit/remove that comment - we are generating them properly. There was a big where we were looking for existing projects in the DB with proj_id = API Code. Overall it's annoying that we don't store the API code though because it would give us near 100% certainty we are dealing with the same project.

**Comment by davidmihalyi** [comment]
gotcha
