### ISSUE TITLE
CH Import: Project metadata

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/ResourceProjects.org#167]
- [x] Consider using transfer locations as project location and get these into the project ID if generated?
- [x] Where to store the project ID once created?

**Comment by davidmihalyi** [comment]
Would option 2 work? Is the data on transfer location there? That seems like a pretty accurate automatic way if info is transfer location info is there.

**Comment by davidmihalyi** [comment]
if we store UK CH project ID, project name in a sheet, we can manually edit country codes missing and then also generate and store RP project ID. Just an idea @mattfullerton

**Comment by mattfullerton** [comment]
Country data on transfers is always there. I'm just trying to think of any cases where that might be misleading?

I think some way of mapping CH project codes to RP project IDs (persistent) would be really good. See also #164.

**Comment by davidmihalyi** [comment]
Then lets use transfers to generate country code, I think it should be right 99% times!
The only problem I could think of is projects that span across two countries and may have transfers to two countries. But we would struggle with that anyways

**Comment by davidmihalyi** [comment]
RE:  I m open to ideas to store CH codes too, if there is a good way.

**Comment by mattfullerton** [comment]
Let's:

- Use transfers when we can't ascertain from project code
- Add an external API code for projects similar to how we store country company number
