### ISSUE TITLE
ETL page and database clean

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#169]
This has all the 0.5 template files, but we`d need 0.6
http://staging.resourceprojects.org/admin/etl/datasets

the imports failed but nevertheless some of it is in the system, which should be deleted.

**Comment by davidmihalyi** [comment]
Matt won`t be able to look at this issue next week, but i won`t be able to review work carried out, until we reload data.

**Comment by mattfullerton** [comment]
NRGI and Smartlane Staging are both cleared out of data. Staging is running staging branch as of last night, Smartlane is running an updated staging with project duplicate detection and latest routing branch merged in. NRGI Staging should then be running that tomorrow.

**Comment by mattfullerton** [comment]
http://staging.resourceprojects.org/admin/etl/datasets

**Comment by davidmihalyi** [comment]
ok, so i should wait until tomorrow before loading onto NRGI staging.

**Comment by davidmihalyi** [comment]
Awesome !
