### ISSUE TITLE
Replace company count with company name list

### ISSUE THREAD

**Issue by anderspeders** [NRGI/ResourceProjects.org#181]
On country pages - for example: http://resourceprojects.org/country/GN companies are currently listed as a number rather than the name. 

Would it make sense to list these not as number but as: [name_company_1; name_company_2] instead? 

![image](https://cloud.githubusercontent.com/assets/1101585/18214974/30538ae4-711d-11e6-8da0-312fe0af9063.png)

**Comment by davidmihalyi** [comment]
This would make sense, especially if count is smaller than 3.

**Comment by davidmihalyi** [comment]
Kseniya.
If company count is 1 : display company name
if company count is 2: display company name with comma separation
if company count is 3 or larger: display text: (count) "companies"

**Comment by anderspeders** [comment]
looks great!

**Comment by anderspeders** [comment]
Suggest that we reopen this ticket based on @davidmihalyi's previous suggestions. 

@KseniyaKuprina what do you think?

**Comment by KseniyaKuprina** [comment]
This functionality is implemented, please test it. Is there anything else that I can work on?

**Comment by anderspeders** [comment]
Thanks - could we do the same for the following page: http://resourceprojects.org/projects?

@davidmihalyi let me know if you agree?

**Comment by davidmihalyi** [comment]
Sure, go ahead @KseniyaKuprina !
