### ISSUE TITLE
transfers page should show all transfers correctly

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#182]
The transfers page currently shows all transfers as if they were related to a project (with level=project and a project name listed). This leads to entries like: 

http://staging.rp.nrgi.smartlane.io:3030/transfers
![image](https://cloud.githubusercontent.com/assets/13120783/18273858/d9c5ecf0-743f-11e6-9875-ec92bf7ecf19.png)
Bakken is a US project, but it shows up in Iran, Nigeria and many other statoil transfers where there is no project name.

In the database, many transfers have no project name assigned  (ie. maybe level=company). 
Hence it should display with blank for project name (instead of multiple Bakken`s).

**Comment by davidmihalyi** [comment]
Sorry my fault but have to reopen this, as now showing duplicates coming from CH data.
Let me think of other solution, that avoids this problem.

**Comment by mattfullerton** [comment]
The controller could use or just pass along into the API data the transfer_level variable. This is set to project or country and should be helpful. If it needs to be more complicated we could also figure out fairly easily if the data came from CH API by populating and using the source property (also not currently passed out to the API by controller). All CH source names begin with "Companies House Extractives Disclosure of"

**Comment by davidmihalyi** [comment]
lets try using transfer_level that would be clean.
   - transfer_level not equal country 

@KseniyaKuprina : let`s discuss on slack tomorrow

**Comment by davidmihalyi** [comment]
so for now as quick fix:
     lets go back to what we had originally.
lets drop those empty lines with no project/site name for now.

**Comment by davidmihalyi** [comment]
"transfer_gov_entity"

**Comment by davidmihalyi** [comment]
Ok. Now that https://github.com/NRGI/ResourceProjects.org/issues/189 is done 
lets fix this list properly.

remove filtering based on project="", site="",
add a filter to display only if transfer_level not equal "country"

**Comment by davidmihalyi** [comment]
also make sure that the level column displays ""transfer_gov_entity" variable.
