### ISSUE TITLE
add wipe data button

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#188]
ETL platform on .. admin/etl/datasets
should get a "delete all data" button.
it should clear the datasets loaded onto platform.

this is only for staging site, given it is quite a dangerous button.

Kseniya please work on this after completed other tasks.
@matt can provide guidance on how this should be done.

**Comment by davidmihalyi** [comment]
@mattfullerton can provide guidance

**Comment by mattfullerton** [comment]
The most exciting thing here is how to find out if your code is running on the staging server ;-)

Beyond that, this code might be helpful:
https://github.com/NRGI/ResourceProjects.org/blob/staging/server/dataprocessing/unloader.js

But what we need here is much simpler; you just go through each model and say [model].remove({})

EXCEPT for countries, commodities, glossarypage, landingpage, sourcetypes, users: these are preset

If in doubt about whether something should be deleted, just ask.
