### ISSUE TITLE
Transfers page edit

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#194]
http://staging.resourceprojects.org/transfers

Make sure the heading "level" is well aligned with rest of table (may need to increase column width slightly).

Please check why "level" column is empty (it refers to variable payment_level ). I would expect it should have value "project" for most entries.

![image](https://cloud.githubusercontent.com/assets/13120783/19223340/9ea4d954-8e6d-11e6-9157-b5965b80d010.png)

**Comment by KseniyaKuprina** [comment]
David, please check my previous, closed tasks https://github.com/NRGI/ResourceProjects.org/issues/182. And that closed task conflicts with this task. Could you please let me know, how this should work for sure? Or you know about this, and want to re-work?

**Comment by davidmihalyi** [comment]
I think the two tasks should be well aligned, following edits 13 days ago.

This is the request from then, which is same as now:
"Ok. Now that #189 is done, lets fix this list properly."
"remove filtering based on project="", site="",
add a filter to display only if transfer_level not equal "country"   "
also make sure that the level column displays ""transfer_gov_entity" variable.

**Comment by davidmihalyi** [comment]
so that transfer level column should be showing any value, except where level="country" (which goes onto a different page)
