### ISSUE TITLE
Modeling notes: placeholder and confirmed projects

### ISSUE THREAD

**Issue by timgdavies** [NRGI/resourceprojects.org#2]
# The puzzle pieces
Much of the data we have about resource projects appears like the pieces of a jigsaw puzzle: fitting together around the edges of a project. Licenses, contracts, companies, oil fields, blocks or mines are all, in theory, related to a project - but very often the project itself is not in view within the data. 

![image](https://cloud.githubusercontent.com/assets/342624/7632432/0101253c-fa1b-11e4-90e9-a432e65b5a1d.png)

Occasionally, a dataset such as those manually constructed from EITI reports, reveal named projects, concretely articulated in the reports from companies. 

## A modelling approach to projects
To respond to this, we should think about modelling two kinds of projects:

* **Placeholder projects** - that can be inferred from other data sources, not not directly discovered in reporting. I.e. the missing jigsaw piece.  
* **Confirmed projects** - that around found directly in a dataset, or that subsequent research has identified and named;

These should live in different URI namespaces on http://resourceprojects.org, with visual design to indicate the distinction. 

In the event a placeholder project becomes recognised as a confirmed project, it would be marked as sameAs the confirmed project, with requests for the placeholder project redirecting to the confirmed project, and it’s properties returned for queries against the confirmed project.

**Comment by anderspeders** [comment]
Great stuff, 

Also dropping a an option for a likely outcome once confirmed:  
- A *confirmed project* where different entitiies define the project under multiple names --> the need for multiple fields for aliases and a selection process for appointing the recommended name space

**Comment by timgdavies** [comment]
See https://github.com/NRGI/resourceprojects.org-frontend/issues/19
