### ISSUE TITLE
Treemap

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#202]
Create treemap on payments per project data.
Here is good template to start:
https://bl.ocks.org/mbostock/4063582

Allow to select (filter) year, currency from drop down.

Levels of treemap:

Paid by- Project -Value (which provides box size) - display value in mililon $
Add a Total million $ value at the bottom (ie. Total: 36,555 million $)

Make sure that only values are used where:
transfer_level not equal "country"

Please provide a standalone HTML link, no need to link to main page  for now

**Comment by davidmihalyi** [comment]
Lets put this on hold, until rest is done, thanks!

**Comment by KseniyaKuprina** [comment]
Link: http://staging.resourceprojects.org/treemap

**Comment by davidmihalyi** [comment]
This works amazingly well!
Can you make it default to 2015 and USD from the filter dropdown?
Thanks
