### ISSUE TITLE
how to retrieve all data in this structure?

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#206]
all projects with following attributes:
project name, project ID, countr (ies), company (ies).

let`s discuss

**Comment by davidmihalyi** [comment]
Please provide link for this one.
d

**Comment by KseniyaKuprina** [comment]
link: http://staging.resourceprojects.org/all-projects

**Comment by davidmihalyi** [comment]
it times out/maxes out at 150 records for me, at letter `B`:
http://www.resourceprojects.org/all-projects
Can you check it?

**Comment by KseniyaKuprina** [comment]
I need access to the prod to do proper debugging. Please share it.

**Comment by davidmihalyi** [comment]
This works well. thanks!
