### ISSUE TITLE
UI suggestion: Add comma to payment amounts

### ISSUE THREAD

**Issue by anderspeders** [NRGI/ResourceProjects.org#207]
Congrats on the UI progress on the site. 

Below a minor small UI suggestions **if there is further bandwith**: 

Consider adding commas (American style?) to payment amounts. For example: **633,804,230** instead of 633804230

Reason: Currently we have a lot of amounts with +7 figures which are difficult to read for the human eye. 

This webservice has similar functionality (as an example):
![image](https://cloud.githubusercontent.com/assets/1101585/19486126/5fdbcca4-952b-11e6-88bf-251fa38b5d76.png)

**Comment by davidmihalyi** [comment]
Please add the comma-s
