### ISSUE TITLE
Contract page, ignore if first column empty

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#215]
Can you ignore displaying record if first column is empty here:
http://new-staging.resourceprojects.org/contracts

Thanks,
David

**Comment by davidmihalyi** [comment]
this was working well, and now it does not display any contracts...
http://www.resourceprojects.org/contracts

**Comment by davidmihalyi** [comment]
works well on staging

**Comment by KseniyaKuprina** [comment]
I need access to the prod to do proper debugging. Please share it.
