### ISSUE TITLE
Payment by recipient download does not work

### ISSUE THREAD

**Issue by anderspeders** [NRGI/ResourceProjects.org#218]
I just downloaded the CSV file for payment by recipient via this page: 
http://resourceprojects.org/transfers_by_gov

The output was an empty file - wonder if this is a bug: 
![image](https://cloud.githubusercontent.com/assets/1101585/19820515/c17824a4-9d27-11e6-8d34-6ca76f17ac66.png)

**Comment by KseniyaKuprina** [comment]
This task is already fixed at staging, so it would be fixed at prod after it's update with last staging version. You can test this at staging, here is the link: http://staging.resourceprojects.org/transfers_by_gov

**Comment by anderspeders** [comment]
@KseniyaKuprina Hi, I just tested this feature again and but data is available. This is all I get from the download: 
![image](https://cloud.githubusercontent.com/assets/1101585/21990606/7c535e76-dbdd-11e6-856e-e80c8a958302.png)

I am downloading from buttom of this page: 
http://resourceprojects.org/transfers_by_gov

**Comment by davidmihalyi** [comment]
@KseniyaKuprina : Please go through download options and check them across different pages (on staging and live).
I failed to dowload this page: /all-projects
Thanks!

**Comment by anderspeders** [comment]
Perfect - thanks!
