### ISSUE TITLE
Tether error in console

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/ResourceProjects.org#224]
On live site, open console, this always comes:
Uncaught SyntaxError: Unexpected identifier utils.js:1

Its coming from the Tether module

**Comment by KseniyaKuprina** [comment]
I need access to the prod to do proper debugging. Please share it.

**Comment by mattfullerton** [comment]
I don't have it and I don't think we can really debug it there. But I consistently get this error on any fresh install of RP.
