### ISSUE TITLE
Consolidate list of payment types:

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#227]
Need to consolidate list of payments at ETL stage
This should be these where possible:
- Fees
- Bonuses
- Royalties
- Tax
- Production Entitlements
- Infrastructure
- Dividends
- Other 
- Total

In order to have that consolidation we should rename payment type values the following 
On the UK CH side:
ensure ProductionEntitlements is renamed Production Entitlements

On the Google Sheet side we should rename:
License fees, rental fees, entry fees, and other considerations for licenses and/or concessions - Fees
Signature, discovery and production bonuses - Bonuses
Production entitlements (can be measured both in volumes ie. barrels and in value) - Production Entitlements
Payments for infrastructure improvements - Infrastructure

**Comment by davidmihalyi** [comment]
Alos linked to: https://github.com/NRGI/ResourceProjects.org/issues/151

**Comment by davidmihalyi** [comment]
@mattfullerton your task is only to fix: ProductionEntitlements  to Production Entitlements

**Comment by davidmihalyi** [comment]
I take that back :) , can you fix both of them easily?
I thought I found the tool to replace across all g-sheet in the folder, but turns out it aint that easy.

**Comment by mattfullerton** [comment]
Note to self: use #governmentReceipt+paymentType+identifier

**Comment by mattfullerton** [comment]
@davidmihalyi I've changed CH to comply

For GS, I'm going to do the following:
if any of:

- Fees
- Bonuses
- Royalties
- Tax
- Production Entitlements
- Infrastructure
- Dividends
- Other
- Total

then use directly

otherwise (all case insensitive searches),

- if "fees" or "license" in the text --> Fees
- if "bonuses" in the text --> Bonuses
- if "entitlements" in the text --> Production Entitlements
- if "infrastructure" in the text --> Infrastructure

If none of those matches, the import will abort with an error you see in the report so the sheet can be checked. Does that sound OK?

**Comment by davidmihalyi** [comment]
Awesome, that works!

**Comment by mattfullerton** [comment]
It would work, but I see the texts are actually based on a sheet lookup so I might just try making direct checks against those and see if there are any problems.

**Comment by mattfullerton** [comment]
Or... do you see any change in the terms coming after the slash? 

- eurd/tax
- eurd/license
- eurd/dividend
- eurd/royalty
- eurd/bonus
- eurd/entitlement
- eurd/infrastructure
- eurd/other
- eurd/total

That would be much cleaner to base it on those, and allow us to change the informative texts (for editors) without affecting the "output" of the sheet.

**Comment by davidmihalyi** [comment]
What would work well is to enforce that if payment type code starts with eurd/ then it enforces strictly that classificiation:
For GS, I'm going to do the following:
if any of:

Fees
Bonuses
Royalties
Tax
Production Entitlements
Infrastructure
Dividends
Other
Total

If it is not eurd/ then use what is in payment type text field
