### ISSUE TITLE
Contract meta data

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#23]
If we have contract data in template in form of ID for RC.org, we should display:
contract name, 
ID, 
link 

as well as following meta data categories:
contract type, 
signature year, 
resource
disclosure mode

**Comment by davidmihalyi** [comment]
all of these should be populated via API query to RC usign RC ID

**Comment by anderspeders** [comment]
Condition for adding to RP: 
Only add contracts *if* document_type="contract"



Example: 
X company signs contract in 2010. In 2015 company payments from B company appears. B may or may not own A.

**Comment by davidmihalyi** [comment]
It is not displaying contract name right now nor here:
http://dev.resourceprojects.org/contracts
nor on project site where there is a link to contract.
http://dev.resourceprojects.org/project/gh-jubi-zpqzhc

**Comment by davidmihalyi** [comment]
probably easiest to fix is the first one (contracts page), other one maybe better to wait post soft launch.

**Comment by byndcivilization** [comment]
These match the wireframe specs. If you want to change these can you add a screenshot of where and what you want?

**Comment by davidmihalyi** [comment]
As a dirty fix, maybe we could change RC-ID to be a link (open in new window)  to appropriate RC contract page?  http://www.resourcecontracts.org/contract/ RC-ID /view

since contract page is empty we don`t really need to display that.

**Comment by byndcivilization** [comment]
moved to #117
