### ISSUE TITLE
Store data on #payment+entity+name

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#238]
@mattfullerton 
I was looking at this, and how the data is being stored: https://github.com/NRGI/ResourceProjects.org/commit/4476647a22f386f94ff34c59a943ca79fc2eebc9
I suspect when #payment+entity+name is "Company" or "Unknown" or "Country" or "" than the data in #payment+entity+name is binned. 
Can we put it into something. (ie "transfer_label") a string so we can display that here:
http://staging.resourceprojects.org/api/transfers/50/0/
"transfer_level": "Company"/"Unknown"/""...,
 "transfer_label": "XYZ"
}

@KseniyaKuprina : Can you add "transfer_level" and this new variable "transfer_label" once Matt fixed it into what comes across the API:
 http://staging.resourceprojects.org/api/transfers/50/0/ http://staging.resourceprojects.org/api/transfersGov/50/0/ 
 
this should stay on staging for now.

**Comment by mattfullerton** [comment]
The assumption in that code is that the #payment+entity+name will be empty or can be ignored. For company or country, do you really need extra data to be stored in a label? For unknown I can understand.

Note that if it is blank ("") and the entity name is set to something (i.e. your label), the first check will be to see if its a project. If not then we go down the same road as "unknown" and could handle the text freely as well.

**Comment by mattfullerton** [comment]
OK, cool.

**Comment by mattfullerton** [comment]
Would it be OK if we do this for production entries as well? I know its not really needed but it would keep the code a bit cleaner and cope with the same situation in the production sheet which theoretically can also come up.

**Comment by mattfullerton** [comment]
Here's a flavour of what we have now:

`{ "_id" : ObjectId("58512c41416598e405241245"), "source" : ObjectId("58512c3e416598e405240fda"), "country" : ObjectId("583f4aedcb98be3815ba4a63"), "transfer_audit_type" : "company_payment", "transfer_level" : "unknown", "transfer_label" : "Other", "transfer_year" : 2015, "transfer_type" : "License fees, rental fees, entry fees, and other considerations for licenses and/or concessions", "transfer_unit" : "USD", "transfer_value" : 79000, "transfer_accounting_basis" : "unknown", "company" : ObjectId("58512c3f416598e405241010"), "__v" : 0 }

{ "_id" : ObjectId("58512c41416598e40524125b"), "source" : ObjectId("58512c3e416598e405240fd2"), "country" : ObjectId("583f4aedcb98be3815ba49ca"), "transfer_audit_type" : "company_payment", "transfer_level" : "unknown", "transfer_label" : "Other oil sands projects", "transfer_year" : 2015, "transfer_type" : "License fees, rental fees, entry fees, and other considerations for licenses and/or concessions", "transfer_unit" : "USD", "transfer_value" : 102000, "transfer_accounting_basis" : "unknown", "transfer_note" : "License Fees", "company" : ObjectId("58512c3f416598e405241022"), "__v" : 0 }

{ "_id" : ObjectId("58512c41416598e40524125d"), "source" : ObjectId("58512c3e416598e405240fcc"), "country" : ObjectId("583f4aedcb98be3815ba4a63"), "transfer_audit_type" : "company_payment", "transfer_level" : "company", "transfer_label" : "AO Karelsky Okatysh", "transfer_year" : 2015, "transfer_type" : "License fees, rental fees, entry fees, and other considerations for licenses and/or concessions", "transfer_unit" : "EUR", "transfer_value" : 103516, "transfer_accounting_basis" : "unknown", "company" : ObjectId("58512c3f416598e40524101c"), "__v" : 0 }

`

**Comment by davidmihalyi** [comment]
Sure, lets do it for production stats too! That works.

**Comment by mattfullerton** [comment]
@KseniyaKuprina Further to the example DB data above, here's an an example of how a record looks with the changes from this issue as well as #227 and #151:

`{ "_id" : ObjectId("585192aea2850103034870e7"), "source" : ObjectId("585192ada285010303486fef"), "country" : ObjectId("583f4aedcb98be3815ba4a8b"), "transfer_audit_type" : "company_payment", "transfer_level" : "company", "transfer_label" : "Corporate", "transfer_year" : 2015, "transfer_type_classification" : "eurd", "transfer_type" : "Other", "transfer_unit" : "USD", "transfer_value" : 13590000, "transfer_accounting_basis" : "unknown", "company" : ObjectId("585192aea285010303486ff2"), "__v" : 0 }`

And how it looks on display right now:
![image](https://cloud.githubusercontent.com/assets/4084428/21197886/614b0de0-c23d-11e6-87dd-3167104c16fa.png)

@davidmihalyi would like level to display properly (it currently wasn't being imported from GS, which was my fault) and transfer_label to appear, somewhere (coordinate with him).

**Comment by davidmihalyi** [comment]
transfer_label should display in project column if project="", but with no hyperlink, just text.
level is now in db to display.
Thanks
