### ISSUE TITLE
Country page improvement

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#241]
The country page has a few things to be corrected or improved.

Looked at this example:
http://staging.resourceprojects.org/country/GB

1) Payments table should be relabeled Payments by Project

2) The payments table has has payments where country not equal GB (I think they are displayed because they were paid by UK company - We should not display those).

3) The payment table does not show level data properly, please correct. Linked to #238 
4) Payment table should display transfer_label where there is no project name (no hyperlink) similarily to treatment of #238 
5) The payment table download should fill out project ID,  project name (if none then transfer_label) and level data correctly.

6) The payment table should hide all records where level="country"
7) Please add another table, below Payments (now Payments by Project) table with title Payments by Recipient
8) This table should be filled out with payment data where level="country", with similar format to table above, but with headers and content of: http://staging.resourceprojects.org/transfers_by_gov

**Comment by KseniyaKuprina** [comment]
David, I have proposal to add one more column to http://staging.resourceprojects.org/countries.
This column will display Payments by project and Payments by receipt (as after doing this task there will be such info)

**Comment by davidmihalyi** [comment]
Great idea, let's do that!

Sent from mobile;  pls excuse brevity and typos.

On 20 Dec 2016, at 09:54, Ksenyia <notifications@github.com<mailto:notifications@github.com>> wrote:


David, I have proposal to add one more column to http://staging.resourceprojects.org/countries.
This column will display Payments by project and Payments by receipt (as after doing this task there will be such info)

-

**Comment by davidmihalyi** [comment]
Can you change the order of columns here:
http://staging.resourceprojects.org/countries
I would like to have this order:
Projects, Payments by Project, Payments by Recipient, Sites, Fields, Concessions.
