### ISSUE TITLE
Treemap Chart improvement

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#242]
Tree Map Chart:

Suggestion
1. Bundle the Filter/Year/Currency/Chart Title/Total in one place for a quicker scan of content and usability
2. Give the overall chart a muted color and a richer hue on rollover
3. Highlight the chart title/name with spacing and line break

smaller font italic _Payments To_
normal Total Dutch Shell PLC
bold **14256.4 Million**

4. Offer a more descriptive/intuitive way to backtrack in the chart
5. Include squares for payments with no project, just a "transfer_label", similarily to sunburst by project. (but don`t display if entity=country)
6. Display the name of the country in brackets next to project name or transfer_label name.

**Comment by KseniyaKuprina** [comment]
David,

considering this point"Bundle the Filter/Year/Currency/Chart Title/Total in one place for a quicker scan of content and usability" - it is already at one place except Total. So just move Total close to Currency?.
Or you mean something else?
2. "Give the overall chart a muted color and a richer hue on rollover" this task will take at least 1. Are you sure you want to do this? As I still had no time for testing latest updates.
4. "Offer a more descriptive/intuitive way to backtrack in the chart" . I can button/arrow "Back" at top right corner of Tree Map Area - agree?
5. Already codded.
6. OK. will do

**Comment by davidmihalyi** [comment]
1. Yes, bring total up and maybe have it all in one box or section.
2. Skip for now then.
4. Great!

**Comment by davidmihalyi** [comment]
Looks great!
Can you change the text on mouse over from "Payment to" to "Payment:"
Thanks,
![image](https://cloud.githubusercontent.com/assets/13120783/21770012/bc7c7e30-d681-11e6-87eb-ba4a4dd37318.png)

**Comment by davidmihalyi** [comment]
Realize that this change also needs to be implemented inside text box (and not just mouse over) 
Change text from "Payment to" to "Payment:"
Thanks
