### ISSUE TITLE
Sunburst chart improvement

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#243]
Sunburst Chart:
1. Bundle the Filter/Year/Currency/Chart Title/Total in one place for a quicker scan of content and usability
2. Give the overall chart a muted color and a richer hue on rollover or offer a legend for the colors. 
3. Make the rollover more informative.
  - Center piece should be labelled All payments  (click to zoom out)
  - Outside pieces should also display the country name, beyond project name
  - The ones with no project name should display "transfer_label" (instead of being labelled corporate as it is now)

**Comment by KseniyaKuprina** [comment]
1. "Bundle the Filter/Year/Currency/Chart Title/Total in one place for a quicker scan of content and usability" it is already at one place. Could please send me screen of how you want this to be?
2. "Give the overall chart a muted color and a richer hue on rollover or offer a legend for the colors." minimum 2 days as it will require updating code of the original plugin to make it custom. Do you confirm that I can use this time for this change?
3. At least half of the day.

**Comment by davidmihalyi** [comment]
1. I would like to have it all on top inside a box. Sorry no screenshot.
2. This is too much. Let`s drop for now.
3. Yes, please do that next week.
