### ISSUE TITLE
Minor changes to payment page

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#245]
On these two pages:
http://resourceprojects.org/transfers_by_gov
http://resourceprojects.org/transfers

1) In the table header rename column: Paid by -> Company
2) In the table header rename column: Paid to -> Country

3) Add a country filter next to other filters, in this order: Year, Currency, Country, Company (rename paid by), Type. 
Default value for country should be show all countries.

4)Put all filters into a box
5) Move the two buttons further up.

**Comment by davidmihalyi** [comment]
Can we have the list in the filter boxes in alphabetical order? (except for show all..)

**Comment by KseniyaKuprina** [comment]
Should I implement such alphabetical filtering at all the pages? Or Just at 2 mentioned in the task?

**Comment by davidmihalyi** [comment]
You are right! lets do it on other dropdowns too, unless it slows down page load significantly.
