### ISSUE TITLE
Fix frontend layout for MS edge

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#247]
The country and project pages seem to break down using Microsoft edge.
Please check for fixes.
![image](https://cloud.githubusercontent.com/assets/13120783/22702146/05a680e8-ed60-11e6-8360-6911cc8a9255.png)

**Comment by KseniyaKuprina** [comment]
While testing at MS Edge, I have found isseu with tree map, will continue testing and fix on Monday
