### ISSUE TITLE
Rethink of download button for pages

### ISSUE THREAD

**Issue by anderspeders** [NRGI/ResourceProjects.org#249]
I have again today tried to access the download button on the project page and must admit that you need to do a lot of scrolling as a user: http://resourceprojects.org/projects

@KseniyaKuprina Would you be able to recommend 1-2 alternatives for where the download feature could be located **as potential alternative**.

**Comment by KseniyaKuprina** [comment]
http://joxi.ru/GrqGMB7CPvx92z
My proposal is to move this button like it is shown at screenshot. 
If you approve - can do this on Monday

**Comment by anderspeders** [comment]
Thanks, this looks good. I assume this could be implemented across download page options?

David: any thoughts from you?

Best,
Anders

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by davidmihalyi** [comment]
Looks good, Kseniya, please go ahead and implement across infinite scroll list related download pages

Thanks

David Mihalyi | Economic Analyst
Natural Resource Governance Institute
Mob (Hu): +36 30 437 6393 | Mob (UK): +44 (0) 77 9858 6290
dmihalyi@resourcegovernance.org<mailto:dmihalyi@resourcegovernance.org> | Twitter: @davidmihalyi | Skype: davidmihalyi
