### ISSUE TITLE
Verified project - Data model

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#3]
Every project entry should have three status of verification
Payment only - where source is UK CH or other payment disclosure
Contextual information - any other source (for now, we will make this rule more complex in next round)
Verified- If project has both payment and context info attached to it.

**Comment by byndcivilization** [comment]
We need to make some decision here. Is there a minimum threshold for either? Do we want this to be human verified? Do we want to store this as a data field or do we want this to be dynamically generated.

**Comment by davidmihalyi** [comment]
I think the human verification element comes in when assigning same project ID to two different information from different sources. Once a project has both type of info assigned, it gets automatically verified.

I would probably go with storing it, so we can later track history of verification changes, especially as that methodology develops.

**Comment by mattfullerton** [comment]
+1 For doing in the controller but including info on when and why it attained this status by pulling in source/etl data

**Comment by davidmihalyi** [comment]
Ok, let`s do it on the controller.

**Comment by davidmihalyi** [comment]
@byndcivilization has a fix for this.
