### ISSUE TITLE
Modelling notes: Key relationships, ontology & reasoning

### ISSUE THREAD

**Issue by timgdavies** [NRGI/resourceprojects.org#3]
There are many relationships between a project and the other entities in our data. At their simplest, these might break down into:

* ```hasComponent``` - relating contracts, companies, concessions, plants etc. to a contract. More specific types might include ```hasParticipant``` (see below), ```relatedContract```, ```relatedLicense``` etc.  
* ```hasParticipant``` - relating a contract, project, concession or plant to an organisational entity. More detailed versions of this might include ```hasParticipatingCompany```, ```hasLeadCompany``` etc.  

* atLocation - relating a contract, project, concession, plan, block etc. to a physical location. Locations themselves should be URIs, which have lat, lng or other bounding-box properties. More detailed versions of location might be ```plantLocation```, ```blockBoundaries``` etc. 

If we develop a simple ontology for capturing these relationships, it should be possible to turn on reasoning in the Virtuoso triple store for queries, meaning that, if you query for all the components (hasComponent) of a project, these are returned, whereas you could also query for more specific elements such as relatedContract only.

**Comment by Bjwebb** [comment]
Are these your all your won terms, or do some of them exist in other ontologies?

As discussed on IRC, it seems like it's only possible to turn on reasoning in virtuoso per query, which makes this more difficult to use with existing tools.
