### ISSUE TITLE
Master template change (from 0.5 to 0.6)

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#33]
This is a list of changes to implement in template 0.6 to be compatible with new data model.

**Comment by davidmihalyi** [comment]
- Add boolean variable on whether a record is a field or a site
- Add open corp id and website to parent company
- Allow a production value or transfer to be linked to a license or field (as opposed to directly to a project)
- Allow for both project and site location ? (currently only site has location in template) - TBD

**Comment by mattfullerton** [comment]
- Open corp ID instead of URL for company
- Companies House ID

**Comment by anderspeders** [comment]
Just flagging how RC tracks companies:

**Comment by mattfullerton** [comment]
In the concessions sheet we are missing company shares. This will be needed to populate concession.concession_company_share and/or concession_operated_by field(s).

**Comment by mattfullerton** [comment]
There is no way to link companies or concessions explicitly to sites, only to projects. In ETL sites for projects are currently found by looking for duplicate project entries with site info. This is OK but makes referencing sites in another sheet difficult I imagine. Not sure what is planned here for the template.

**Comment by mattfullerton** [comment]
Concession commodities are foreseen by the model but not in the 0.6 template

**Comment by davidmihalyi** [comment]
Add source types to list of options, as based on https://github.com/NRGI/rp-org-frontend/issues/11

**Comment by mattfullerton** [comment]
Enforce % for company shares of concessions

**Comment by mattfullerton** [comment]
See also #34 for ETL implications (needs updated)

**Comment by mattfullerton** [comment]
Open Oil contract ID

**Comment by mattfullerton** [comment]
Don't ask for RC URL and the contract ID, but do provide a URL field where ID does not exist/is not known

**Comment by mattfullerton** [comment]
Maybe use open corporates ID instead of URL. On the other hand URL is easier to paste for contributors and ID extraction is easy.

**Comment by mattfullerton** [comment]
No way to set company shares/operators on sites, only projects

**Comment by mattfullerton** [comment]
Especially if a site has multiple commodities, site info becomes scattered across rows. This should stop.
