### ISSUE TITLE
404 page is not styled unless it's at top level

### ISSUE THREAD

**Issue by Bjwebb** [NRGI/resourceprojects.org#33]
http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/a is styled.
http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/a/b is not.

**Comment by Bjwebb** [comment]
Moved to https://github.com/NRGI/resourceprojects.org/issues/33

**Comment by caprenter** [comment]
We're going to deal with this by setting all the dependency URLs in the header to / instead of {{lodspeakr.home}}

**Comment by caprenter** [comment]
duplicate of https://github.com/NRGI/resourceprojects.org-frontend/issues/77
