### ISSUE TITLE
ETL: Link companies and concessions (and who knows what else) to sites and not just projects

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/ResourceProjects.org#35]

**Comment by mattfullerton** [comment]
Note that this is not currently possible with the spreadsheet template - the three Cs are only linked to projects, not individual sites.

**Comment by byndcivilization** [comment]
Yeah in some ways this is future proofing for other custom loads. I think a super easy win would be to do an index of RC.org. Another one is concession pulls from OO or from other registry sources.

**Comment by mattfullerton** [comment]
There is now comprehensive linking amongst all of company, project, contract, concession and site. The code is also much much easier to read.
