### ISSUE TITLE
ETL (GS): Identify columns by name or identifier, not number

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/ResourceProjects.org#46]
Name or #identifier?

Its not ideal that the column headings appear in different places and that they don't appear in the first row.

**Comment by davidmihalyi** [comment]
column IDs (#identifier) should all and always appear in row 4 and their text name in row 3.
better to use them as the column number

**Comment by mattfullerton** [comment]
Sheets 7 (Concessions/Contracts/Companies) and 10 (Payments/Receipts) do not adhere to this.

**Comment by mattfullerton** [comment]
Suggest moving this to milestone that is linked with 0.6 template usage.

**Comment by davidmihalyi** [comment]
Sure!
