### ISSUE TITLE
Project type should be determined by commodity

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/ResourceProjects.org#47]
This is a fact array and i think comes from #commodity+commodityType on the project sheet. I've set acceptable values at mining and oil_and_gas.

**Comment by mattfullerton** [comment]
Why do we need this when we already have commodity fact array? Should it be identical to that? Is this future proofing?

**Comment by byndcivilization** [comment]
Actually your right, we're storing this on the commodity. I' pull form there. Will it kill anything if I remove it from the model?

**Comment by mattfullerton** [comment]
Not on my side, and the controller (what I have here anyway) doesn't seem to reference it. Not sure about the angular side.

**Comment by byndcivilization** [comment]
awesome ill kill it and pull from commodity

**Comment by davidmihalyi** [comment]
sorry I did not catch what was happening here....

Right now where commodity is missing it blanks out the type variable too even if we have it in sheet. 

When in exploration stage and unknown what commodity will be found, we still know type.
We had a type value for 100% of projects but only approx 75% coverage on commodity.

Not ideal to blank out where we do have value, but maybe too cumbersome to fix now?

**Comment by davidmihalyi** [comment]
I can do some dirty fix adding oil for every oil and gas project or we can park for launch.

**Comment by davidmihalyi** [comment]
Adding oil for these but will need to go back to revision history and fix.
