### ISSUE TITLE
Define revenue types - if possible

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourceprojects.org#6]
This might not be urgent, but useful to have on the radar. 

A few data collection methods are already beeing applied: 
1) EITI International secretariat is using the GFSM 2014 revenue classification: https://eiti.org/document/eiti-summary-data-template

2) The revenue types provided under the EU Accounting Directive (insert note)

**Comment by davidmihalyi** [comment]
Revenue types in company reporting under EU directive are the following: 
• Production entitlements (can be measured both in volumes ie. barrels and in value)
• Taxes levied on the income, production or profits of companies,
• Royalties
• Dividends
• Signature, discovery and production bonuses 
• License fees, rental fees, entry fees, and other considerations for licenses and/or concessions
• Payments for infrastructure improvements

http://www.ey.com/Publication/vwLUAssets/EY_-_Disclosing_government_payments_for_natural_resource_extraction/$FILE/EY-Disclosing-government-payments.pdf

**Comment by davidmihalyi** [comment]
It is a bit messy, as reporting may have a little bit different breakdown across jurisdictions, although generally pretty much the same content, just different labels and splits. (royalties, bonus payments, fees, production entitlement, dividends, infrastructure payment, all pretty much appear under same name. Taxes levied on the income, production or profits of companies may often be broken down and labeled differently. Additional types of payments may be added on top.

**Comment by davidmihalyi** [comment]
Besides currency (or volume metric) it is worth noting if payment was recorded on "cash" or "accrual" basis, if information is available.

**Comment by timgdavies** [comment]
@davidmihalyi What would be an appropriate property name for whether payment was on 'cash' or 'accrual' basis? 

Would ```paymentBasis``` be sensible?

Are there any other options it could have other than cash / accrual.

**Comment by davidmihalyi** [comment]
I think officially it is called basis of accounting, but PaymentBasis sounds perfect.
I would say cash / accrual / unknown / other

**Comment by timgdavies** [comment]
In this spreadsheet https://docs.google.com/spreadsheets/d/1zEqqjv3ifCDQKjqSCpzqoBJ6hAhl_OO9u0eXfryIGUg/edit#gid=913907526 I've mapped the GFSM and EU Accounting Directive code lists, and assigned identifiers to each. 

At present, on import a user should choose between which scheme they are using, and data will be recorded against that scheme.

We could look at structuring the GFSM as a clearer hierarchical concept list in future within the datastore, making it possible to aggregate up payments to a higher level, allowing data to be mapped between the two schemes if we have data for a single company recorded in the different schemes - though we will have to be careful about double-counting here.
