### ISSUE TITLE
Reconcile w company`s house API

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#6]
Show matches and partial matches (exact match of first word) for both project names and company names. Allow user to confirm all or some of the matches.

**Comment by byndcivilization** [comment]
might be able to get this done with https://www.npmjs.com/package/fuzzy or https://www.npmjs.com/package/fuzzy-matching or https://github.com/krisk/Fuse

**Comment by byndcivilization** [comment]
linked to #7

**Comment by byndcivilization** [comment]
moved to #113
