### ISSUE TITLE
Project list should get a CSV download

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#68]
http://dev.resourceprojects.org/projects 

this would also allow to do simple visualization for slides on what types of projects we have on the site.
@byndcivilization : is this tricky?

**Comment by byndcivilization** [comment]
yes an no but no time before soft launch

**Comment by davidmihalyi** [comment]
OK!

**Comment by byndcivilization** [comment]
moved to #118
