### ISSUE TITLE
Adding contracts that are URLs

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#69]
Peru has a few contracts that are not stored on RC.org but are just URLs.
Lets try how they look if we ETLd URL, but might look bad and will need to drop.

**Comment by byndcivilization** [comment]
Can a quick fix just be to add these to RC? @anderspeders ?

**Comment by davidmihalyi** [comment]
It is quite a few contract to link up (33 outstanding).
I`ve linked three of them together , but then realized that subsequent ones were often dirty matches, which required more careful look. @anderspeders have a look for yourself.
https://docs.google.com/spreadsheets/d/1gl3syhKsI-pR_lx3KykuKOLnHrp7ir2fRxjaPTO3DgM/edit#gid=1333644202

**Comment by mattfullerton** [comment]
There's a slight problem with this - all contract data is taken from RC, so when we create a contract without a RC URL, we see no data about the contract, just mostly empty rows, which we can't even click on to get to the contract. I'm not sure there's a quick fix as contracts are being pulled in in quite a few places.

**Comment by mattfullerton** [comment]
Assigning this to @byndcivilization to make decision on whether to rework controllers to take account of contracts without RC IDs.

**Comment by davidmihalyi** [comment]
Lets park this and move to hard launch

**Comment by byndcivilization** [comment]
moved to #119
