### ISSUE TITLE
ETL: Be more persistant with project IDs

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/ResourceProjects.org#70]
So that they don't get reassigned upon a new import, ideally

**Comment by byndcivilization** [comment]
will this really be an issue with a stable prod db?

**Comment by davidmihalyi** [comment]
If we wanted to have other people use our project-ID as reference or API queries, we should make sure they are stable. We can discuss this post launch.

**Comment by byndcivilization** [comment]
no thats not what i mean. Right now we're dealing with a dev db that gets periodically wiped to check on new etl. once we move to a stable deployment, we will have a production db that wont get wiped and reset. so there wont be new project ids generated.

**Comment by davidmihalyi** [comment]
I think we will have to make a choice on being able to have agile solution at editing existing content (without wiping out project IDs) or store them somewhere. Right now only way to edit is to wipe data and reset with new project IDs

**Comment by byndcivilization** [comment]
i dont totally get this. we shouldnt need to edit really right? we import data and leave it in there. I think we will need some sort of provenance model for admin edits but otherwise data needs to persist, because there are a bunch of internal ids that cant be ephemeral becuase they are used for joins essentially.

**Comment by byndcivilization** [comment]
disaster recovery is daily db backups and record versioning. We can at some point add another layer i guess of porting stuff out to ckan also but that seems like overkill.

**Comment by byndcivilization** [comment]
Closing this. Post hard launch we will no longer reload database.
