### ISSUE TITLE
Project map

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#80]
This might need to wait for after soft launch but we slacked about project map needing to pull both site and field location. Right now it is empty, so if not fixing it we might want to take it off.
http://dev.resourceprojects.org/projects/map

The site and field map used to work but they were removed.

**Comment by byndcivilization** [comment]
mostly works but needs to be refined for hard launch

**Comment by davidmihalyi** [comment]
Amazing!
