### ISSUE TITLE
Project count duplication

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/ResourceProjects.org#81]
I hit import button on the DNO company file (Norwegian companies) twice

it led to duplicate count on project page:
DNO Iraq has 3 project not 6
DNO yemen has 5 not 10 projects
http://dev.resourceprojects.org/company/56fc03df1ca3ee0100580a45

![image](https://cloud.githubusercontent.com/assets/13120783/14151871/fa77b0ac-f6a7-11e5-9354-87f4e96aa5b1.png)

**Comment by mattfullerton** [comment]
Double loads are now prevented at the html-page level: can we hence move this to hard launch?

**Comment by davidmihalyi** [comment]
Awesome thanks!
