### ISSUE TITLE
public api

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/ResourceProjects.org#92]
The public API needs to be cleaned up, locked down and documented.

**Comment by davidmihalyi** [comment]
- This record in API is mislabeled:
https://github.com/NRGI/ResourceProjects.org/wiki/GET-Country-By-ID
It fetches commodity details, not country details.
-It would be quite important  to be able to retrieve all project data for one country only.
This would probably be one of most useful query for building analysis or visual on top.

**Comment by davidmihalyi** [comment]
Public API much improved, currently documented further.
